### PR TITLE
Release 1.3

### PR DESCRIPTION
**Pull request by kain88-de**
Updates to the newest release and includes the license file in the package.

@jakirkham do you mind checking if this meets all of your best practices.

### CODE REVIEW

**Comment by kain88-de** [comment]
Does only the creation of the PR already push a new version to the conda-forge channel?

**Comment by ocefpaf** [comment]
> Does only the creation of the PR already push a new version to the conda-forge channel?

Nope. But as soon as we merge it will. Also, updates like this are fair game to be self-merged.

Thanks @kain88-d!

**Comment by ocefpaf** [comment]
Ah... Now that I see you did not sent this from a fork. So the CIs not only started twice but the binaries were updated before the merge.

Next time do a fork-branch-PR approach to avoid uploading a package that is not 100% ready to the channel.

**Comment by kain88-de** [comment]
yeah I figured that later myself. But wouldn't it be safer to disable push builds for everything but the master branch.

**Comment by ocefpaf** [comment]
> But wouldn't it be safer to disable push builds for everything but the master branch.

That idea floated around. I lost track of the reasons to why or why not. Please feel free to raise that point again here: https://github.com/conda-forge/conda-forge.github.io/issues

**Pull request merged**
